name: 'Lint / Build / Test'
description: 'lint, format, typecheck, build, and test'

inputs:
  skip-steps:
    description: "Format is comma-seperated steps to skip. Example: 'build,typecheck'"
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: '🧹 Lint'
      shell: bash
      if: ${{ !contains(inputs.skip-steps, 'lint') }}
      run: bunx biome check --apply .

    - name: '🧹 Format'
      shell: bash
      if: ${{ !contains(inputs.skip-steps, 'format') }}
      run: bunx biome format . --write

    - name: '🧪 Typecheck'
      shell: bash
      if: ${{ !contains(inputs.skip-steps, 'typecheck') }}
      run: bun run typecheck

    - name: '🔧 Build'
      shell: bash
      if: ${{ !contains(inputs.skip-steps, 'build') }}
      run: bun run build

    - name: '🧪 Test'
      shell: bash
      if: ${{ !contains(inputs.skip-steps, 'test') }}
      run: bun test
